red = (0, 0, 255)
blue = (255, 0, 0)
green =(0, 255, 0)
white = (250,250,250)
hand_width_factor = 1.2
hand_opening_factor = 1.3
skip_frames = 100
hand_status_buffer_size = 10
video_folder = r'..\test_videos [gitignore]/'
moving_speed = 2 # pixel per frame, min needed to be detected as moving hand
gui_hight = 1/4 # of the frame hight
arm_decection_border_top = 1/4 # of the frame hight
arm_decection_border_bot = 1/4 # of the frame hight
cam_angle_hight = {0:1.70, 32.5:2.60} # if the cam has the angle x° it is mounted in the hight y m